GET http://localhost:9000/users
Content-Type: application/json


###
POST http://localhost:9000/users
Content-Type: application/json


{
    "name":"hiral",
    "email":"test2@test.com",
    "password":"test1234"
}

###
PATCH  http://localhost:9000/users/5
Content-Type:  application/json

{
    "name":"hiral1234",
    "email":"test1@test.com",
    "password":"test1234"
}
###
DELETE http://localhost:9000/users/7
Accept: application/json
###
POST http://localhost:9000/users/login
Content-Type: application/json

{
    "name":"hiral",
    "email":"test@test.com",
    "password":"test1234"
}
